version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=bankcards_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-u postgres", "-d bankcards_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bankcards-net

  bankcards-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankcards-app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bankcards_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bankcards-net

volumes:
  postgres_data:

networks:
  bankcards-net: