version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=bankcards_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-u postgres", "-d bankcards_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bankcards-net

  bankcards-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankcards-app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bankcards_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
      - CARD_ENCRYPTION_SECRET_KEY=N1PCdw3M2B1TfJhoaY2mL736p2vCUc47
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bankcards-net

volumes:
  postgres_data:

networks:
  bankcards-net: